### ISSUE TITLE
Rename to extension to gmtplot

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/sphinx_gmt#19]
The name of the module `gmtplot` is different from the actual directive `gmt-plot`. It would probably be easier if everything was `gmtplot` instead so we could include links to the API docs when mentioning the directive using `:mod:` links.

**Comment by seisman** [comment]
What if we want to add some other directives (e.g. gmt-gallery) in the future?

**Comment by leouieda** [comment]
@seisman sorry, I meant to rename `gmt-plot` to `gmtplot` so that the extension name matches `sphinx_gmt/gmtplot.py`. If we do a gallery extension, it could be `gmtgallery` and the module would be `sphinx_gmt/gmtgallery.py`.

**Comment by seisman** [comment]
I thought you're proposing to rename the whole package to `gmtplot`. Sorry to misunderstand what you mean.

Renaming the directive `gmt-plot` to `gmtplot` is OK to me.
